auth - done
zhdima/goit-nodejs-hw-02-06-rest-api pull request #3
Opened 2023-05-27 11:58 UTC by zhdima

Please check it

2023-05-27 16:12 UTC, ceREAL133 requested changes

2023-05-27 16:12 UTC, ceREAL133 commented on controllers/users-controller
what's the point of having this file. It's junk. Please delete it

2023-05-27 22:14 UTC, zhdima commented on controllers/users-controller
Що Ви маєте на увазі? Що стосується users-controller - це файл контролерів, що відповідають за управління списком користувачів, в нашому випадку - тільки за зміну плану підписки, тобто за  зміну поля subscription в коллекції користувачів.
Таким чином, маємо два різні направлення роботи з користувачами - аутентифікація та безпосередньо робота з їх параметрами, як наприклад, зміна плану підписки. Тобто, розділяємо це на два контролери - auth-controller та users-controllrer.
Тобто users-controllrer використоувується для зміни параметрів користувача, як задано в додатковому завданні - для оновлення плану підписки, а auth-controller - для завдань аутентифікації.

2023-05-27 22:22 UTC, zhdima commented on controllers/users-controller
Тобто це реалізація додаткового завдання - Оновлення підписки (subscription) користувача через ендпоінт PATCH /users

2023-05-28 05:48 UTC, ceREAL133 commented on controllers/users-controller
Реальний контактс контроллер- вище. А це файл без розширення. Він ніде не використовується

2023-05-28 07:32 UTC, zhdima commented on controllers/users-controller
Це не контактс контроллер, а контролер користувачів. Він використовується в апі для обробки роутів роботи з користувачами (в нашому випадку поки тільки оновлення їх subscription) users-routes.js:
const userController = require("../../controllers/users-controller");
Так, я чомусь зробив його без розширення js, це я підправив, дякую.
Звісно, всю його невеличку поки функціональність можна було зробити в auth-controller.js, але я вирішив таким чином розділити логіку реєстрації/аутентифікації та безпосередньо редагування профілів користувачів, та й маршрути в них різні (auth та users). Якщо наполягаєте - я можу їх об'єднати, це не принципово )

2023-05-28 07:41 UTC, ceREAL133 commented on controllers/users-controller
Ні, обʼєднувати не треба, у мене тільки питання, яким чином він використовувався, якщо був без розширення?

2023-05-28 07:47 UTC, zhdima commented on controllers/users-controller
В users-routes.js:
const userController = require("../../controllers/users-controller");
Ми же ніколи розширення js не вказуємо, коли імпортуємо, його автоматично система додасть, ну от і вийшло, що файл без розширення чітко імпортується, як він є, навіть системі нічого не потрібно додавати ))

2023-05-28 11:16 UTC, ceREAL133 approved these changes

2023-06-02 18:15 UTC, merged